# Generated by Django 6.0.6 on 2026-06-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeilingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=50)),
                ('so_date', models.DateField(blank=True, null=True)),
                ('medicine_name', models.CharField(max_length=500)),
                ('strength', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('ceiling_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('wpi_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('effective_from', models.DateField()),
                ('financial_year', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['medicine_name'], name='drugs_ceili_medicin_2a0b46_idx'), models.Index(fields=['financial_year'], name='drugs_ceili_financi_55349c_idx'), models.Index(fields=['so_number'], name='drugs_ceili_so_numb_d6b81c_idx')],
            },
        ),
    ]
