# Generated by Django 6.0.6 on 2026-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceilingprice',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='ceilingprice',
            name='strength',
        ),
        migrations.AddField(
            model_name='ceilingprice',
            name='dosage_form_and_strength',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
