# Generated by Django 6.0.6 on 2026-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_remove_ceilingprice_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceilingprice',
            name='ceiling_price',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ceilingprice',
            name='wpi_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
