# Generated by Django 6.0.6 on 2026-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_alter_ceilingprice_ceiling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceilingprice',
            name='row_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceilingprice',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
