# Generated by Django 6.0.6 on 2026-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_ceilingprice_row_number_ceilingprice_source_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLEMEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nlem_version', models.CharField(default='2022', max_length=10)),
                ('sl_no', models.CharField(max_length=20)),
                ('medicine', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=300)),
                ('dosage_form_and_strength', models.TextField(blank=True)),
                ('level_of_healthcare', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'NLEM entry',
                'verbose_name_plural': 'NLEM entries',
                'ordering': ['nlem_version', 'sl_no'],
                'indexes': [models.Index(fields=['medicine'], name='drugs_nleme_medicin_dc0a0d_idx'), models.Index(fields=['category'], name='drugs_nleme_categor_d4f599_idx'), models.Index(fields=['nlem_version'], name='drugs_nleme_nlem_ve_ab49eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('nlem_version', 'sl_no'), name='unique_nlem_version_slno')],
            },
        ),
    ]
