# Generated by Django 6.0.6 on 2026-06-17 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFiveJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='form5_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_review', 'Waiting for Review'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_group', models.CharField(blank=True, default='', max_length=255)),
                ('log', models.TextField(default='')),
                ('flagged_rows', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
